version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 18
  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 661659055102.dkr.ecr.us-east-1.amazonaws.com
      
      # הגדרת נתיבי ה-Repositories
      - BACKEND_REPO=661659055102.dkr.ecr.us-east-1.amazonaws.com/jewelry-backend
      - AUTH_REPO=661659055102.dkr.ecr.us-east-1.amazonaws.com/jewelry-auth

  build:
    commands:
      - echo Build started on `date`
      - echo Building Backend Docker image...
      - docker build -t $BACKEND_REPO:latest ./backend
      
      - echo Building Auth Service Docker image...
      - docker build -t $AUTH_REPO:latest ./auth-service
      
      - echo Building Frontend from jewelry-store directory...
      # שינוי כאן: כניסה לתיקייה הנכונה
      - cd jewelry-store && npm install && npm run build && cd ..

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $BACKEND_REPO:latest
      - docker push $AUTH_REPO:latest
      
      - echo Uploading to S3...
      # שינוי כאן: הנתיב המקור הוא jewelry-store/dist
      - aws s3 sync ./jewelry-store/dist s3://my-static-site-roieharkavi-2026 --delete
      
      - echo Invalidating CloudFront...
      - aws cloudfront create-invalidation --distribution-id d3ak4fwjnqldtt --paths "/*"
      
      - echo Updating manifests...
      - printf '[{"name":"backend","imageUri":"%s"},{"name":"auth","imageUri":"%s"}]' $BACKEND_REPO:latest $AUTH_REPO:latest > imagedefinitions.json

artifacts:
  files:
    - '**/*'
