version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_REGION=us-east-1
      - AWS_ACCOUNT_ID=661659055102
      # שיניתי כאן לשם שמופיע אצלך בצילום מסך
      - REPO_NAME=jewelry-backend
      - REPO_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image for Backend...
      # וודא שהתיקייה בגיטהאב אכן נקראת backend
      - docker build -t $REPO_URL:latest ./backend
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPO_URL:latest
      - printf '{"ImageURI":"%s"}' $REPO_URL:latest > imageDetail.json
artifacts:
  files:
    - imageDetail.json
