version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query Account --output text).dkr.ecr.us-east-1.amazonaws.com
      - REPO_URL=$(aws sts get-caller-identity --query Account --output text).dkr.ecr.us-east-1.amazonaws.com/roieharkavi-repo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      # כאן השינוי: אנחנו מצביעים לתיקייה שבה נמצא ה-Dockerfile
      # תחליף את 'backend' בשם התיקייה המדויק שלך (למשל 'backend-service' או 'server')
      - docker build -t $REPO_URL:latest ./backend
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_URL:latest
      - echo Creating imageDetail.json...
      - printf '{"ImageURI":"%s"}' $REPO_URL:latest > imageDetail.json
artifacts:
  files:
    - imageDetail.json
