version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 18
  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      # הגדרת משתני עזר (וודא שהם מוגדרים ב-CodeBuild Environment Variables)
      - BACKEND_REPO=$REPOSITORY_URI_BACKEND
      - AUTH_REPO=$REPOSITORY_URI_AUTH

  build:
    commands:
      - echo Build started on `date`
      
      # 1. בניית ה-Backend
      - echo Building Backend Docker image...
      - docker build -t $BACKEND_REPO:latest ./backend
      
      # 2. בניית ה-Auth Service
      - echo Building Auth Service Docker image...
      - docker build -t $AUTH_REPO:latest ./auth-service
      
      # 3. בניית ה-Frontend (קבצים סטטיים)
      - echo Building Frontend...
      # וודא שהתיקייה נקראת בדיוק frontend בגיטהאב שלך
      - cd frontend && npm install && npm run build && cd ..

  post_build:
    commands:
      - echo Build completed on `date`
      
      # דחיפת האימג'ים ל-ECR
      - docker push $BACKEND_REPO:latest
      - docker push $AUTH_REPO:latest
      
      # --- תיקון והוספה מכאן ---
      
      # 4. העלאת הפרונטנד ל-S3
      - echo Uploading to S3...
      # וודא שתיקיית הפלט היא אכן dist (ב-React/Vite זה dist, ב-Angular זה dist/project-name)
      - aws s3 sync ./frontend/dist s3://my-static-site-roieharkavi-2026 --delete
      
      # 5. ניקוי ה-Cache של CloudFront (הפקודה החדשה)
      - echo Invalidating CloudFront cache so changes reflect immediately...
      # החלף את YOUR_DISTRIBUTION_ID ב-d3ak4fwjnqldtt (או השתמש במשתנה סביבה)
      - aws cloudfront create-invalidation --distribution-id d3ak4fwjnqldtt --paths "/*"
      
      # עדכון ה-Manifests עבור ArgoCD
      - echo Updating manifests...
      - printf '[{"name":"backend","imageUri":"%s"},{"name":"auth","imageUri":"%s"}]' $BACKEND_REPO:latest $AUTH_REPO:latest > imagedefinitions.json

artifacts:
  files:
    - '**/*'
