version: '3.8'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - jewelry-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 10s
      retries: 10
      start_period: 30s

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jewelry-net
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - DOCKER_HOST=tcp://jenkins-docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - jewelry-net
    restart: unless-stopped

  auth-service:
    image: localhost:8082/repository/docker-hosted/jewelry-app/auth-service:staging
    container_name: auth-service
    ports:
      - "8001:8001"
    depends_on:
      nexus:
        condition: service_healthy
    networks:
      - jewelry-net
    restart: unless-stopped

  backend:
    image: localhost:8082/repository/docker-hosted/jewelry-app/backend:staging
    container_name: backend-service
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started
      nexus:
        condition: service_healthy
    networks:
      - jewelry-net
    restart: unless-stopped
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001

  frontend:
    image: localhost:8082/repository/docker-hosted/jewelry-app/frontend:staging
    container_name: frontend-nginx
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
      auth-service:
        condition: service_started
      nexus:
        condition: service_healthy
    networks:
      - jewelry-net
    restart: unless-stopped

volumes:
  nexus-data:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jewelry-net:
    driver: bridge
