services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: roieharkavi/jewelry-app:auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET_KEY=your-secret-key-here
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - jewelry-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: roieharkavi/jewelry-app:backend
    container_name: backend-service
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=your-secret-key-here
      - AUTH_SERVICE_URL=http://auth-service:8001
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - auth-service
    networks:
      - jewelry-network
    restart: unless-stopped

  frontend:
    build:
      context: ./jewelry-store
      dockerfile: Dockerfile
    image: roieharkavi/jewelry-app:frontend
    container_name: frontend-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - auth-service
    networks:
      - jewelry-network
    restart: unless-stopped

networks:
  jewelry-network:
    driver: bridge

volumes:
  nginx_cache:
    driver: local
