# -------------------------
# Stage 1: Installer (amazonlinux)
# -------------------------
FROM amazonlinux:2 as installer

# התקנת aws-cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && yum update -y \
    && yum install -y unzip curl \
    && unzip awscliv2.zip \
    && ./aws/install --bin-dir /aws-cli-bin/

# התקנת Snyk
RUN mkdir /snyk && cd /snyk \
    && curl https://static.snyk.io/cli/v1.666.0/snyk-linux -o snyk \
    && chmod +x ./snyk

# -------------------------
# Stage 2: Jenkins Agent
# -------------------------
FROM jenkins/agent:latest

# העתקת הכל מה-installer
COPY --from=installer /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=installer /aws-cli-bin/ /usr/local/bin/
COPY --from=installer /snyk/ /usr/local/bin/
COPY --from=installer /snyk/ /usr/bin/

# שינוי ל-root כדי להוסיף את jenkins לקבוצת docker
USER root

# יצירת קבוצה docker אם היא לא קיימת והוספת המשתמש jenkins
RUN groupadd -f docker && usermod -aG docker jenkins

# התקנת python3 ו-pip
RUN apt-get update && apt-get install -y python3 python3-pip

# חזרה ל-user jenkins
USER jenkins

# ברירת מחדל: שינה ל- sleep infinity, מאפשר ל-agent להחזיק את עצמו
CMD ["sleep", "infinity"]
