version: "3.9"

services:
  # -------------------------
  # Jenkins Server
  # -------------------------
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - jewelry-net
    restart: unless-stopped

  # -------------------------
  # Jenkins Agent
  # -------------------------
  jenkins-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins-agent
    privileged: true
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - jenkins-data:/var/jenkins_home
    networks:
      - jewelry-net
    restart: unless-stopped
    command: ["sleep", "infinity"]
    depends_on:
      - jenkins
      - nexus

  # -------------------------
  # Nexus Repository
  # -------------------------
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"   # UI
      - "8082:8082"   # Docker registry
    volumes:
      - nexus-data:/nexus-data
    networks:
      - jewelry-net
    restart: unless-stopped

networks:
  jewelry-net:

volumes:
  jenkins-data:
    driver: local
    driver_opts:
      type: none
      device: /home/roie/jenkins-data
      o: bind
  nexus-data:
    driver: local
    driver_opts:
      type: none
      device: /home/roie/nexus-data
      o: bind
