version: '3.8'

services:
  auth-service:
    image: nexus:8082/repository/docker-hosted/jewelry-app:auth-service
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET_KEY=your-secret-key-here
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - jewelry-network

  backend:
    image: nexus:8082/repository/docker-hosted/jewelry-app:backend
    container_name: backend-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=your-secret-key-here
      - AUTH_SERVICE_URL=http://auth-service:8001
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - auth-service
    networks:
      - jewelry-network

  frontend:
    image: nexus:8082/repository/docker-hosted/jewelry-app:frontend
    container_name: frontend-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
      - auth-service
    networks:
      - jewelry-network

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: unless-stopped
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://jenkins-docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081" 
      - "8082:8082" 
    volumes:
      - nexus-data:/nexus-data
    networks:
      - jenkins
      - jewelry-network

networks:
  jewelry-network:
    driver: bridge
  jenkins:
    driver: bridge

volumes:
  nginx_cache:
    driver: local
  jenkins-data:
  jenkins-docker-certs:
  nexus-data:
